[project]
name = "R-image-plotter"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sibbe Bakker <sibbe.bakker@wur.nl>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
pictuR = "Rscript pictuR.R --help"

[dependencies]
r-cli = ">=3.6.3,<3.7"
shiny = ">=1.0.0,<1.1"
r-shiny = ">=1.9.1,<1.10"
r-shinyjs = ">=2.1.0,<2.2"
r-shinywidgets = ">=0.8.6,<0.9"
r-ggtext = ">=0.1.2,<0.2"
r-ggplot2 = ">=3.5.1,<3.6"
r-gridextra = ">=2.3,<3"
r-magick = ">=2.8.4,<2.9"
r-tidyverse = ">=2.0.0,<2.1"
r-argparse = ">=2.2.3,<2.3"
